apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: SFIA2
  namespace: sfia2-namespace
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: backend