apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: SFIA2-Namespace
  labels:
    app: SFIA2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aadil/backend:latest
        ports:
        - containerPort: 5001