apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sfia2-namespace
data:
  nginx.conf:
    server {
      listen 80;
      location / {
        proxy_pass http://flask-app:5000
      }
    }