apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: SFIA2
  namespace: SFIA2-Namespace
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: frontend