apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: SFIA2
  namespace: sfia2-namespace
spec:
  selector:
    matchLabels:
      app: SFIA2
  replicas: 3
  template:
    metadata:
      labels:
        app: SFIA2
    spec:
      containers:
      - name: frontend
        image: aadilmoghal/frontend:latest
        ports:
        - containerPort: 5000