apiVersion: apps/v1
kind: deployment
metadata:
  name: frontend
  labels:
    app: SFIA2
  namespace: sfia2-namespace
spec:
  selector:
    matchLabels:
      app: SFIA2
  template:
    metadata:
      labels:
        app: SFIA2
spec:
  replicas: 3
  containers:
  - name: frontend
    image: aadilmoghal/frontend:latest
    ports:
    - containerPort: 5000