apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: SFIA2-Namespace
  labels:
    app: flask

spec: 
  selector: 
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer