all:
  hosts:
    3.10.205.80:
  vars:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: '~/.ssh/aws-key.pem'

jenkins:
  hosts:
    35.177.32.99:
  vars:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: '~/.ssh/aws-key.pem'